name: nit_validator
description: A simple tool for offline check nit number, this use an simple algorithm to check if this is ok and returns a boolean according to the input.
version: 1.0.2
homepage: https://github.com/box-bm/nit_validator
repository: https://github.com/box-bm/nit_validator
issue_tracker: https://github.com/box-bm/nit_validator/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
